# Generated by scripts/homebrew-formula.sh in onushq/onus; do not edit by hand.
class Onus < Formula
  desc "Turns a pull request into a short report of changes in meaning"
  homepage "https://onushq.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/onushq/onus/releases/download/v0.2.0/onus-aarch64-apple-darwin.tar.gz"
      sha256 "987236f9773be18b3fdb471a281789318a7d49c880626e182cd46d1f6e99fe5d"
    end
    on_intel do
      url "https://github.com/onushq/onus/releases/download/v0.2.0/onus-x86_64-apple-darwin.tar.gz"
      sha256 "a9e08ac9eb7b16b01f02f64cbbca419240f1485ceb3247e0a151f63fb114fe23"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/onushq/onus/releases/download/v0.2.0/onus-aarch64-unknown-linux-musl.tar.gz"
      sha256 "823209ba180372325ca7bc71d914ac2eaa3035117fc12deef185ebe937c62d22"
    end
    on_intel do
      url "https://github.com/onushq/onus/releases/download/v0.2.0/onus-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2862a1f1d34c743e9c53ff0c94d254f45b6aebc482f17f3bd79b0687c9e6d7d1"
    end
  end

  def install
    bin.install "onus", "onus-plugin-svelte"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onus --version")
    (testpath/"pkg/package.json").write '{"name":"pkg","main":"index.ts"}'
    (testpath/"pkg/index.ts").write "export function hello(): string { return 'hi'; }\n"
    assert_match "1 symbols", shell_output("#{bin}/onus map #{testpath}/pkg")
  end
end
