# Generated by scripts/homebrew-formula.sh in onushq/onus; do not edit by hand.
class Onus < Formula
  desc "Turns a pull request into a short report of changes in meaning"
  homepage "https://onushq.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/onushq/onus/releases/download/v0.8.0/onus-aarch64-apple-darwin.tar.gz"
      sha256 "117fd3f8eeac8535d102e21249c48b88034477c64dabc8088069cc841d594567"
    end
    on_intel do
      url "https://github.com/onushq/onus/releases/download/v0.8.0/onus-x86_64-apple-darwin.tar.gz"
      sha256 "6e09acbdb4653129eb8e3b69b2ca1a2433aa9109f66ff9a333849b0fb3e1ad10"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/onushq/onus/releases/download/v0.8.0/onus-aarch64-unknown-linux-musl.tar.gz"
      sha256 "d32902531a87e1c3633609a46a160052aa898f67b4a242ee41205acee96a2beb"
    end
    on_intel do
      url "https://github.com/onushq/onus/releases/download/v0.8.0/onus-x86_64-unknown-linux-musl.tar.gz"
      sha256 "6d3a087801f30a47a6277705420ff3a8ed0d4c8baf35e2f7f22b7a6976afaed6"
    end
  end

  def install
    bin.install "onus", "onus-plugin-svelte"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onus --version")
    (testpath/"pkg/package.json").write '{"name":"pkg","main":"index.ts"}'
    (testpath/"pkg/index.ts").write "export function hello(): string { return 'hi'; }\n"
    assert_match "1 symbols", shell_output("#{bin}/onus map #{testpath}/pkg")
  end
end
