# Generated by scripts/homebrew-formula.sh in onushq/onus; do not edit by hand.
class Onus < Formula
  desc "Turns a pull request into a short report of changes in meaning"
  homepage "https://onushq.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/onushq/onus/releases/download/v0.9.0/onus-aarch64-apple-darwin.tar.gz"
      sha256 "648f8c864cc3b36ee58c923ab9d89af243b1436258ace5138992fb9a1ed3f3ea"
    end
    on_intel do
      url "https://github.com/onushq/onus/releases/download/v0.9.0/onus-x86_64-apple-darwin.tar.gz"
      sha256 "ead090f8b135f17603939132556426a473f2998b4bbe4c49a26e091a0fe7198c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/onushq/onus/releases/download/v0.9.0/onus-aarch64-unknown-linux-musl.tar.gz"
      sha256 "938e7d8516bfe8f9ea15893dabec2702b18e662c5a57731ef159ed89515ab8ad"
    end
    on_intel do
      url "https://github.com/onushq/onus/releases/download/v0.9.0/onus-x86_64-unknown-linux-musl.tar.gz"
      sha256 "17aafe5c99612a32e21e5f33861a0e87a2946219e337237cab3bdf507db66404"
    end
  end

  def install
    bin.install "onus", "onus-plugin-svelte"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/onus --version")
    (testpath/"pkg/package.json").write '{"name":"pkg","main":"index.ts"}'
    (testpath/"pkg/index.ts").write "export function hello(): string { return 'hi'; }\n"
    assert_match "1 symbols", shell_output("#{bin}/onus map #{testpath}/pkg")
  end
end
